### ISSUE TITLE
Will this support Chinese？

### ISSUE THREAD

**Issue by jilanlan** [BzenkoSergey/ng-cron#25]

**Comment by BzenkoSergey** [comment]
Can be added, it is not a big deal.

I think this should not support a particular language.
Let's call it localization, by default it can only support English, but it has the ability to change the localization as you want.

@jilanlan which version are you using react or angular?

**Comment by jilanlan** [comment]
Sorry to reply late. I am using react and the version is "16.12.0".  
And I have another question for U, when I set the initial value of the component，the tab group didn't show correctly, the "Seconds" is always active. I feel perplexed.

**Comment by NadeSi** [comment]
How can i change localization in react project?

**Comment by BzenkoSergey** [comment]
New version 1.0.1 supports localization for both react and angular.
React Doc: https://bzenkosergey.github.io/ng-cron/react/#/doc/localization
Angular Doc: https://bzenkosergey.github.io/ng-cron/angular/#/doc/localization
