### ISSUE TITLE
feature request: add a prop showYear

### ISSUE THREAD

**Issue by tobiasjeckel** [BzenkoSergey/ng-cron#36]
Hi,
would it be possible to add a prop like 'showYear: true | false' that allows for deactivation of the 'year' tab and thus receive cron strings with 6 fields ? 
Thanks

**Comment by BzenkoSergey** [comment]
> Hi,
> would it be possible to add a prop like 'showYear: true | false' that allows for deactivation of the 'year' tab and thus receive cron strings with 6 fields ?
> Thanks

Good idea but for now try to use css to hide elements you don't want to see.

**Comment by BzenkoSergey** [comment]
Added tabs managing prop `tabs`, just pass tabs you want to show.
```
import { ReCron, Tab } from '@sbzen/re-cron';

<ReCron tabs={[Tab.MINUTES, Tab.HOURS]} />
```

Doc: https://bzenkosergey.github.io/ng-cron/react/#/doc/customization/visibility-props
