### ISSUE TITLE
angular 10 ivy complain error

### ISSUE THREAD

**Issue by LinBoLen** [BzenkoSergey/ng-cron#38]
Error: Error on worker #4: Error: Failed to find exported name of node (class MinuteComponent extends TabSingleSegmentComponent {
    /**
     * @param {?} coreService
     * @param {?} cd
     * @param {?} quartzCron
     */
    constructor(coreService, cd, quartzCron) {
        super(Segment.minutes, quartzCron, cd);
        this.coreService = coreService;
        this.minuteCodes = this.coreService.getList(Segment.minutes, true);
        this.minutes = this.coreService.getList(Segment.minutes);
    }

**Comment by BzenkoSergey** [comment]
> Error: Error on worker #4: Error: Failed to find exported name of node (class MinuteComponent extends TabSingleSegmentComponent {
> /**
> * @param {?} coreService
> * @param {?} cd
> * @param {?} quartzCron
> */
> constructor(coreService, cd, quartzCron) {
> super(Segment.minutes, quartzCron, cd);
> this.coreService = coreService;
> this.minuteCodes = this.coreService.getList(Segment.minutes, true);
> this.minutes = this.coreService.getList(Segment.minutes);
> }

Thanks for this report! please use @sbzen/ng-cron version 0.0.10
