### ISSUE TITLE
plugin breaks when Wednesday is the only specific day of week selected

### ISSUE THREAD

**Issue by BDRDev** [BzenkoSergey/ng-cron#45]
steps to recreate:
1. Select the "Day" tab
2. Select "Specific day of week" option
3. Select "Wednesday" then deselect all other options 

the "Specific day of week" section will then no longer let me select/deselect any other options
can be recreated on the demo site - https://bzenkosergey.github.io/ng-cron/react/#/

**Comment by BzenkoSergey** [comment]
Thanks! this issue is fixed in @sbzen/re-cron@1.0.1
