### ISSUE TITLE
Plugin generates Incorrect Cron Quartz expression

### ISSUE THREAD

**Issue by OmarZayed98** [BzenkoSergey/ng-cron#51]
We recently upgraded from 0.0.7 version to 1.0.1, and we have seen some differences in the expression.

for example to re-create: 
1) Choose every second, every minute and every hour and any year
2) For day choose 2 or more days from the "Specific day of the week"
3) For month choose 2 or more months from the "specific month"
for version 0.0.7 the output was the following: " * * * ? JAN,FEB SUN,MON"
for version 1.0.1 the output was the following: "* * * * JAN,FEB SUN,MON"
It added '*' instead of '?' and according to https://www.freeformatter.com/cron-expression-generator-quartz.html the 0.0.7 version was correct.

-The issue also happens with different steps and different combinations in the day and months. for example picking days from "clicking Specific day of month (choose one or many) "

**Comment by BzenkoSergey** [comment]
@OmarZayed98 Thanks!
Try version 1.0.3, it contains fixes that cover this bug.
