### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by Ghost-Programmer** [BzenkoSergey/ng-cron#56]
![cron](https://user-images.githubusercontent.com/8131029/115948266-2e621c80-a49b-11eb-9665-75fc05d77631.png)

Getting this layout of your Cron and I'm struggling to figure out why.  

1. I have imported QuartzCronModule
2. I added the following to a new component as the only HTML in the component: `<div>
	<quartz-cron class="my-vertical-cron"></quartz-cron>
</div>`

**Comment by BzenkoSergey** [comment]
@Ghost-Programmer Do you use bootstrap?
https://getbootstrap.com/

**Comment by Ghost-Programmer** [comment]
That should be in your documentation.  But unfortunately, that makes this unusable for my application, as Bootstrap conflicts with Angular Material too much.

**Comment by BzenkoSergey** [comment]
@Ghost-Programmer
Bootstrap is an optional dependency that covers styles.
You can still use ng-cron but it will require your own styles.

This case described in documentation:
https://bzenkosergey.github.io/ng-cron/angular/#/doc/customization/css-styling#whole-redesign
