### ISSUE TITLE
Component crashes with expression with a range (e.g. MON-FRI)

### ISSUE THREAD

**Issue by mattludma** [BzenkoSergey/ng-cron#60]
If I try to edit expression with a range of values (for example `0 40 7 ? * MON-FRI *`), the component crashes with error `Cannot set property 'mode' of undefined`

There are two levels to this problem:
1) GUI of the dialog currently does not support generating and displaying ranges of values. This is not that big of a deal, because you can select all the values fron the range manually (e.g. MON,TUE,WED,THU,FRI)
2) Component crashes when range is entered. This problem is more important. Better outcome would be to load the component and leave the problematic tab not filled. Version 0.0.8 used to work like this.

**Comment by BzenkoSergey** [comment]
@mattludma  Sorry for long response, this issue is fixed in version 1.0.5.
![image](https://user-images.githubusercontent.com/5772034/119243268-da1b8c80-bb6d-11eb-89d9-d143423eef4e.png)
