### ISSUE TITLE
Error when choose july

### ISSUE THREAD

**Issue by anthoinguyen** [BzenkoSergey/ng-cron#68]
When i choose Specific month is july, it auto choose every moon. I can't choose Specific month is july

**Comment by BoykaZhu** [comment]
I can see the same issue.

"react": "17.0.2",
"@sbzen/re-cron": "^1.0.5",

**Comment by anthoinguyen** [comment]
You can use trick to fix it: 
<ReCron
        value={cronValue.replace( "JUL", "JUL," )}
        onChange={setCronValue} 
/>

**Comment by BzenkoSergey** [comment]
@anthoinguyen @BoykaZhu 
Issue fixed in @sbzen/re-cron version 1.0.6
