### ISSUE TITLE
See the year rang is from 2019, possible to current year

### ISSUE THREAD

**Issue by BoykaZhu** [BzenkoSergey/ng-cron#69]
See the year range is from 2019, possible to dynamic current year in sbzen-cron-core.js?

**Comment by BzenkoSergey** [comment]
@BoykaZhu added `renderYearsFrom` and `renderYearsTo` to cover your needs.
Use @sbzen/re-cron version 1.0.6.

Example:
https://stackblitz.com/edit/react-ts-ttzdy4?file=index.tsx
